"""Lexicon y conjuntos auxiliares para la traducción inicial."""
from __future__ import annotations

LEXICON: dict[str, str] = {
    "hola": "HOLA",
    "buenos": "BUENO",
    "buenas": "BUENO",
    "dias": "DIA",
    "tardes": "TARDE",
    "noches": "NOCHE",
    "gracias": "GRACIAS",
    "por": "POR",
    "favor": "FAVOR",
    "porfavor": "POR FAVOR",
    "bien": "BIEN",
    "mal": "MAL",
    "salud": "SALUD",
    "ayuda": "AYUDA",
    "porfa": "POR FAVOR",
    "si": "SI",
    "sí": "SI",
    "no": "NEG",
    "porqué": "POR-QUE",
    "porque": "POR-QUE",
    "que": "QUE",
    "qué": "QUE",
    "como": "COMO",
    "cómo": "COMO",
    "cuando": "CUANDO",
    "cuándo": "CUANDO",
    "donde": "DONDE",
    "dónde": "DONDE",
    "quien": "QUIEN",
    "quién": "QUIEN",
    "cuanto": "CUANTO",
    "cuánto": "CUANTO",
    "cuantos": "CUANTO",
    "cuántos": "CUANTO",
    "porque": "POR-QUE",
    "grande": "GRANDE",
    "pequeno": "PEQUEÑO",
    "pequeño": "PEQUEÑO",
    "manana": "MAÑANA",
    "mañana": "MAÑANA",
    "tarde": "TARDE",
    "noche": "NOCHE",
    "hoy": "HOY",
    "ayer": "AYER",
    "manana": "MAÑANA",
    "yo": "YO",
    "tu": "TU",
    "tú": "TU",
    "usted": "USTED",
    "ustedes": "USTEDES",
    "nosotros": "NOSOTROS",
    "nosotras": "NOSOTRAS",
    "ellos": "ELLOS",
    "ellas": "ELLAS",
    "el": "EL",
    "él": "EL",
    "ella": "ELLA",
    "ser": "SER",
    "soy": "SER",
    "eres": "SER",
    "es": "SER",
    "somos": "SER",
    "son": "SER",
    "estar": "ESTAR",
    "estoy": "ESTAR",
    "estas": "ESTAR",
    "estás": "ESTAR",
    "esta": "ESTAR",
    "está": "ESTAR",
    "estamos": "ESTAR",
    "estan": "ESTAR",
    "están": "ESTAR",
    "tener": "TENER",
    "tengo": "TENER",
    "tienes": "TENER",
    "tiene": "TENER",
    "tenemos": "TENER",
    "tienen": "TENER",
    "querer": "QUERER",
    "quiero": "QUERER",
    "quieres": "QUERER",
    "quiere": "QUERER",
    "quieren": "QUERER",
    "necesitar": "NECESITAR",
    "necesito": "NECESITAR",
    "necesitas": "NECESITAR",
    "llamar": "LLAMAR",
    "llamo": "LLAMAR",
    "llamas": "LLAMAR",
    "ver": "VER",
    "verbo": "VER",
    "trabajar": "TRABAJAR",
    "trabajo": "TRABAJAR",
    "trabajas": "TRABAJAR",
    "trabaja": "TRABAJAR",
    "colegio": "ESCUELA",
    "universidad": "UNIVERSIDAD",
    "doctor": "DOCTOR",
    "hospital": "HOSPITAL",
    "casa": "CASA",
    "familia": "FAMILIA",
    "amigo": "AMIGO",
    "amiga": "AMIGO",
    "amigos": "AMIGO",
    "comunidad": "COMUNIDAD",
    "urgente": "URGENTE",
    "ayuda": "AYUDA",
    "escuela": "ESCUELA",
    "la": "LA",
    "en": "EN",
    "registrar": "REGISTRAR",
    "sera": "SER",
    "será": "SER",
    "tramite": "TRAMITE",
    "trámite": "TRAMITE",
    "documento": "DOCUMENTO",
    "documentos": "DOCUMENTO",
    "ayuntamiento": "ALCALDIA",
    "alcaldia": "ALCALDIA",
    "alcaldía": "ALCALDIA",
    "registro": "REGISTRO",
    "oficina": "OFICINA",
    "negativo": "NEG",
    "nunca": "NEG",
    "jamás": "NEG",
    "jamaz": "NEG",
    "siempre": "SIEMPRE",
    "ahora": "AHORA",
    "luego": "LUEGO",
    "despues": "DESPUES",
    "después": "DESPUES",
    "manana": "MAÑANA",
    "mañana": "MAÑANA",
    "tarde": "TARDE",
    "noche": "NOCHE",
    "ayer": "AYER",
    "hoy": "HOY",
    "accion": "ACCION",
    "acción": "ACCION",
    "urgencia": "URGENTE",
    "medico": "DOCTOR",
    "médico": "DOCTOR",
    "clinica": "CLINICA",
    "clínica": "CLINICA",
}

PRONOUNS: set[str] = {
    "yo",
    "tu",
    "tú",
    "usted",
    "ustedes",
    "nosotros",
    "nosotras",
    "ellos",
    "ellas",
    "el",
    "él",
    "ella",
}

QUESTION_WORDS: set[str] = {
    "como",
    "cómo",
    "cuando",
    "cuándo",
    "donde",
    "dónde",
    "que",
    "qué",
    "quien",
    "quién",
    "cuanto",
    "cuánto",
    "porqué",
    "porque",
}
